---
- name: install common APT pkgs
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - sudo
    - ntp
    - ntpdate
    - htop
    - less
    - lsof
    - strace
    - tcpdump
    - vim
