---
- name: apt upgrade
  apt:
    upgrade: 'yes'

- name: install common apt pkgs
  apt:
    name: ['sudo', 'ntp', 'ntpdate','htop', 'less', 'lsof', 'strace', 'tcpdump', 'vim']
    state: present
    update_cache: yes

